### ISSUE TITLE
UI/UX Enhancement

### ISSUE THREAD

**Issue by navaneethkrishna30** [navaneethkrishna30/WhisperZone#1]
I'm open to any new UI/UX suggestions

**Comment by rishyym0927** [comment]
Hey @navaneethkrishna30  I wanna work on this issue can you assign me this issue.

**Comment by rishi-harti768** [comment]
@navaneethkrishna30 Hey can you assign me this issue?

**Comment by navaneethkrishna30** [comment]
ok is this the same person? if yes, to which account should i assign the issue?

**Comment by rishi-harti768** [comment]
Yes I'm the same person and you can assign to this account
