### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by navaneethkrishna30** [navaneethkrishna30/WhisperZone#2]

**Comment by rishyym0927** [comment]
Hey @navaneethkrishna30  I wanna work on this issue, can you please assign it to me?

**Comment by yashksaini-coder** [comment]
hi @rishyym0927 can I work on this issue first as it is involved in the #5 so there are some changes I need to first. Once I am done re-creating the README documentation, you can raise another issue to improve it overall.  

how does that sounds ? 
@navaneethkrishna30 can you assign this issue to me to make my necessary changes

**Comment by yashksaini-coder** [comment]
Hi @navaneethkrishna30 let me work on this issue as this requries changes involved in #5
