### ISSUE TITLE
Add More Tests

### ISSUE THREAD

**Issue by navaneethkrishna30** [navaneethkrishna30/WhisperZone#3]
Improve test coverage for the backend (especially for edge cases like invalid input handling). I'm looking for unit and integration tests for the chat room logic.

**Comment by Prithwi32** [comment]
@navaneethkrishna30 I would like to work on this issue, please could you assign it to me under hacktoberfest.
If I need to discuss where shall I contact..

**Comment by navaneethkrishna30** [comment]
you can reach out to me via Linkedin https://www.linkedin.com/in/navaneethkrishnamudumba/

**Comment by Prithwi32** [comment]
@navaneethkrishna30 its completed right, can u close this issue
