### ISSUE TITLE
Improve Error Handling on the backend

### ISSUE THREAD

**Issue by navaneethkrishna30** [navaneethkrishna30/WhisperZone#4]
Show popups or notifications for users when they encounter issues (e.g., server unreachable, room doesn't exist) or provide better feedback when any of the services are not reachable

**Comment by rishyym0927** [comment]
I have a good command over node js and have worked on multiple projects. I guess I am very much eligible to take on this project.

**Comment by yashksaini-coder** [comment]
> the backend is written in flask. if you are willing to learn error handling in python, please do take up the issue

I have good knowledge over python and flask. I would like to contribute to this project

**Comment by navaneethkrishna30** [comment]
Go ahead @yashksaini-coder

**Comment by yashksaini-coder** [comment]
> Go ahead @yashksaini-coder

thx @navaneethkrishna30
