### ISSUE TITLE
Static page site

### ISSUE THREAD

**Issue by yashksaini-coder** [navaneethkrishna30/WhisperZone#5]
@navaneethkrishna30 I can also you have a issue #2 for documentation. I would like to contribute on a issue that also enhances your project. by giving it a static page website that can be easily build & deploy. using Github actions. 

This would enhance the project.

---

I would like to work on this issue so can you assign this to me & add labels. I can get started on working once the #2 is resolved.

**Comment by navaneethkrishna30** [comment]
I was thinking about using Vercel for frontend. If i change my mind, I'll reopen the issue and assign it to you.

**Comment by navaneethkrishna30** [comment]
What content does the static page website contain? Is it for documentation?

**Comment by yashksaini-coder** [comment]
> What content does the static page website contain? Is it for documentation?

Normally I can create a jekyll theme based docs site that renders markdown files.

**Comment by navaneethkrishna30** [comment]
Sure! Go ahead..
